# Generated by Django 3.0.2 on 2020-01-12 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 12, 47, 13, 536712)),
        ),
    ]
