# Generated by Django 3.0.2 on 2020-02-19 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0002_auto_20200112_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='url',
        ),
        migrations.AlterField(
            model_name='logs',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 22, 8, 13, 28827)),
        ),
    ]
